import { db, propertyCount } from "./index.js";
import { currentTimestampIso } from "../lib/time.js";
import type { Property, PropertyPurpose, PropertyType } from "../types/property.js";

type SeedProperty = Omit<Property, "createdAt" | "purpose" | "propertyType" | "condominium" | "code">;

const IMG = {
  p1: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80&auto=format&fit=crop",
  p2: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
  p3: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80&auto=format&fit=crop",
};

const SEED_PROPERTIES: SeedProperty[] = [
  {
    slug: "casa-em-condominio",
    title: "Casa em Condomínio",
    location: "Alphaville, São Paulo - SP",
    address: "Alameda Rio Negro, 500 — Alphaville, Barueri - SP",
    badge: "DESTAQUE",
    image: IMG.p1,
    gallery: [
      IMG.p1,
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 5,
    parking: 3,
    area: 320,
    price: "R$ 2.850.000",
    priceValue: 2_850_000,
    description: [
      "Residência de alto padrão em condomínio fechado, com arquitetura contemporânea e acabamentos de primeira linha. Ambientes amplos e integrados, com pé-direito duplo na sala de estar e iluminação natural abundante.",
      "A área externa conta com piscina aquecida, espaço gourmet completo e jardim paisagístico — ideal para receber família e amigos com conforto e privacidade.",
      "Localizada em uma das regiões mais valorizadas de Alphaville, próxima a escolas internacionais, shoppings e principais vias de acesso.",
    ],
    features: [
      { label: "Piscina", icon: "pool" },
      { label: "Área gourmet", icon: "gourmet" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Jardim", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "3 vagas", icon: "parking" },
    ],
  },
  {
    slug: "edificio-lotus-residence",
    title: "Edifício Lótus Residence",
    location: "Centro, São Paulo - SP",
    address: "Rua Augusta, 1200 — Consolação, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: IMG.p2,
    gallery: [
      IMG.p2,
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 3,
    parking: 2,
    area: 110,
    price: "R$ 1.150.000",
    priceValue: 1_150_000,
    description: [
      "Lançamento exclusivo no coração de São Paulo, com plantas inteligentes e vista panorâmica da cidade. O Edifício Lótus Residence combina design sofisticado com tecnologia de ponta.",
      "Apartamentos com varanda gourmet, cozinha integrada e suíte master com closet. Áreas comuns incluem rooftop com piscina, salão de festas e coworking.",
      "Excelente localização com fácil acesso ao metrô, restaurantes, teatros e principais centros empresariais da região central.",
    ],
    features: [
      { label: "Piscina", icon: "pool" },
      { label: "Varanda gourmet", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Coworking", icon: "wifi" },
      { label: "Elevador social", icon: "elevator" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-premium",
    title: "Apartamento Premium",
    location: "Vila Mariana, São Paulo - SP",
    address: "Rua Domingos de Morais, 2564 — Vila Mariana, São Paulo - SP",
    image: IMG.p3,
    gallery: [
      IMG.p3,
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 2,
    baths: 2,
    parking: 1,
    area: 75,
    price: "R$ 780.000",
    priceValue: 780_000,
    description: [
      "Apartamento reformado com bom gosto, em prédio bem conservado na Vila Mariana. Ambientes claros e arejados, com piso em porcelanato e iluminação LED em todos os cômodos.",
      "Cozinha americana com bancada em quartzo, sala ampla com varanda e dois dormitórios, sendo um suíte. Perfeito para casais ou pequenas famílias.",
      "Região completa em infraestrutura: metrô a poucos minutos, hospitais, parques e comércio variado nas proximidades.",
    ],
    features: [
      { label: "Varanda", icon: "balcony" },
      { label: "Cozinha americana", icon: "gourmet" },
      { label: "Portaria", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Área de lazer", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "Elevador", icon: "elevator" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "cobertura-duplex-jardins",
    title: "Cobertura Duplex nos Jardins",
    location: "Jardins, São Paulo - SP",
    address: "Alameda Santos, 1827 — Jardins, São Paulo - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 5,
    parking: 4,
    area: 380,
    price: "R$ 5.200.000",
    priceValue: 5_200_000,
    description: [
      "Cobertura duplex de luxo com vista permanente para o Parque Trianon. O piso superior abriga suíte master com closet, banheira de hidromassagem e terraço privativo com jacuzzi.",
      "Piso inferior com sala de estar de 80 m², jantar formal, cozinha gourmet com ilha em mármore e lavabo social. Acabamento em madeira nobre e automação residencial completa.",
      "Prédio icônico nos Jardins com apenas duas unidades por andar, portaria com concierge e acesso direto às melhores boutiques e restaurantes da cidade.",
    ],
    features: [
      { label: "Jacuzzi", icon: "pool" },
      { label: "Terraço gourmet", icon: "gourmet" },
      { label: "Concierge 24h", icon: "security" },
      { label: "Automação", icon: "ac" },
      { label: "Fitness", icon: "gym" },
      { label: "Vista parque", icon: "balcony" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "4 vagas", icon: "parking" },
    ],
  },
  {
    slug: "studio-moderno-pinheiros",
    title: "Studio Moderno em Pinheiros",
    location: "Pinheiros, São Paulo - SP",
    address: "Rua dos Pinheiros, 498 — Pinheiros, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 1,
    baths: 1,
    parking: 1,
    area: 42,
    price: "R$ 520.000",
    priceValue: 520_000,
    description: [
      "Studio compacto e funcional, ideal para jovens profissionais. Ambiente integrado com cozinha planejada, bancada em granito e armários sob medida.",
      "Prédio novo com rooftop, lavanderia compartilhada e bicicletário. A poucos passos da estação Pinheiros e do centro gastronômico da região.",
      "Excelente opção para investimento com alta demanda de locação na região.",
    ],
    features: [
      { label: "Rooftop", icon: "balcony" },
      { label: "Cozinha planejada", icon: "gourmet" },
      { label: "Portaria", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Lavanderia", icon: "gym" },
      { label: "Bicicletário", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "casa-de-campo-atibaia",
    title: "Casa de Campo em Atibaia",
    location: "Atibaia, São Paulo - SP",
    address: "Estrada Municipal do Piracuama, 1200 — Atibaia - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 5,
    baths: 4,
    parking: 4,
    area: 450,
    price: "R$ 1.890.000",
    priceValue: 1_890_000,
    description: [
      "Refúgio perfeito para fins de semana e feriados, com 2.000 m² de terreno arborizado e vista para a Serra da Mantiqueira.",
      "Casa térrea com varanda envolvente, lareira na sala, cozinha caipira ampla e quiosque com churrasqueira e forno de pizza.",
      "A 80 km de São Paulo, com fácil acesso pela Rodovia Fernão Dias. Condomínio com portaria e lago para pesca esportiva.",
    ],
    features: [
      { label: "Piscina", icon: "pool" },
      { label: "Churrasqueira", icon: "gourmet" },
      { label: "Portaria", icon: "security" },
      { label: "Lareira", icon: "ac" },
      { label: "Quiosque", icon: "garden" },
      { label: "Vista serra", icon: "balcony" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "4 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-frente-mar-santos",
    title: "Apartamento Frente Mar em Santos",
    location: "Gonzaga, Santos - SP",
    address: "Av. Bartolomeu de Gusmão, 110 — Gonzaga, Santos - SP",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 2,
    parking: 2,
    area: 130,
    price: "R$ 1.420.000",
    priceValue: 1_420_000,
    description: [
      "Apartamento com vista definitiva para o mar, a apenas 50 metros da praia do Gonzaga. Sacada ampla voltada para o oceano em todos os ambientes sociais.",
      "Três dormitórios com armários embutidos, sendo uma suíte com hidromassagem. Sala em L com dois ambientes e cozinha com despensa.",
      "Prédio frente mar com piscina, salão de festas e zeladoria. Região com infraestrutura completa de comércio, restaurantes e ciclovia.",
    ],
    features: [
      { label: "Vista mar", icon: "balcony" },
      { label: "Sacada ampla", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Piscina", icon: "pool" },
      { label: "Salão festas", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "loft-industrial-vila-madalena",
    title: "Loft Industrial na Vila Madalena",
    location: "Vila Madalena, São Paulo - SP",
    address: "Rua Harmonia, 856 — Vila Madalena, São Paulo - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 2,
    baths: 2,
    parking: 2,
    area: 145,
    price: "R$ 1.680.000",
    priceValue: 1_680_000,
    description: [
      "Loft em edifício reconvertido de antiga fábrica textil, com pé-direito de 4,5 metros e janelas originais em arco. Design autoral com tijolos aparentes e estrutura metálica.",
      "Mezanino com home office e quarto de hóspedes. Cozinha gourmet aberta com ilha central e adega climatizada embutida.",
      "No coração da Vila Madalena, cercado por galerias de arte, bares e o Beco do Batman. Um dos endereços mais desejados de São Paulo.",
    ],
    features: [
      { label: "Pé-direito duplo", icon: "balcony" },
      { label: "Cozinha gourmet", icon: "gourmet" },
      { label: "Segurança", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Adega", icon: "garden" },
      { label: "Home office", icon: "wifi" },
      { label: "Elevador", icon: "elevator" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "mansao-alto-padrao-morumbi",
    title: "Mansão de Alto Padrão no Morumbi",
    location: "Morumbi, São Paulo - SP",
    address: "Rua Professor Manoelito de Ornellas, 55 — Morumbi, São Paulo - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 6,
    baths: 8,
    parking: 6,
    area: 680,
    price: "R$ 12.500.000",
    priceValue: 12_500_000,
    description: [
      "Propriedade excepcional em terreno de 1.800 m² no Morumbi, com projeto assinado por renomado escritório de arquitetura. Fachada em vidro e concreto aparente.",
      "Seis suítes, cinema privativo, spa com sauna e sala de massagem, adega para 500 garrafas e elevador panorâmico interno.",
      "Jardim com piscina de borda infinita, quadra de tênis e horta orgânica. Segurança reforçada com CFTV e monitoramento 24 horas.",
    ],
    features: [
      { label: "Piscina infinita", icon: "pool" },
      { label: "Spa privativo", icon: "gourmet" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Cinema", icon: "ac" },
      { label: "Quadra tênis", icon: "gym" },
      { label: "Horta orgânica", icon: "garden" },
      { label: "Automação", icon: "wifi" },
      { label: "6 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-garden-moema",
    title: "Apartamento Garden em Moema",
    location: "Moema, São Paulo - SP",
    address: "Alameda dos Nhambiquaras, 533 — Moema, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 3,
    parking: 3,
    area: 195,
    price: "R$ 2.350.000",
    priceValue: 2_350_000,
    description: [
      "Apartamento garden no térreo com 120 m² de área externa privativa, paisagismo completo e deck de madeira. Sensação de casa com a segurança de condomínio.",
      "Três suítes, sala com três ambientes, cozinha gourmet integrada e lavabo. Iluminação zenital em corredores e banheiros.",
      "Moema é referência em qualidade de vida em São Paulo, com parques, escolas renomadas e o Shopping Ibirapuera nas proximidades.",
    ],
    features: [
      { label: "Garden privativo", icon: "garden" },
      { label: "Deck madeira", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Piscina cond.", icon: "pool" },
      { label: "Playground", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "3 vagas", icon: "parking" },
    ],
  },
  {
    slug: "casa-terrea-granja-viana",
    title: "Casa Térrea em Granja Viana",
    location: "Granja Viana, Cotia - SP",
    address: "Alameda Paineiras, 220 — Granja Viana, Cotia - SP",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 3,
    parking: 4,
    area: 280,
    price: "R$ 1.650.000",
    priceValue: 1_650_000,
    description: [
      "Casa térrea em condomínio fechado de Granja Viana, com terreno de 500 m² e quintal gramado. Ideal para famílias que buscam tranquilidade sem abrir mão da cidade.",
      "Quatro dormitórios, sendo duas suítes, escritório, sala de TV e cozinha com despensa. Área de serviço coberta e depósito.",
      "Condomínio com clube completo: piscinas, quadras, salão de festas e trilha ecológica. A 30 minutos do Morumbi.",
    ],
    features: [
      { label: "Piscina clube", icon: "pool" },
      { label: "Churrasqueira", icon: "gourmet" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Quintal", icon: "garden" },
      { label: "Escritório", icon: "wifi" },
      { label: "Clube", icon: "gym" },
      { label: "4 vagas", icon: "parking" },
    ],
  },
  {
    slug: "flat-mobiliado-itaim-bibi",
    title: "Flat Mobiliado no Itaim Bibi",
    location: "Itaim Bibi, São Paulo - SP",
    address: "Rua Bandeira Paulista, 726 — Itaim Bibi, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 1,
    baths: 1,
    parking: 1,
    area: 48,
    price: "R$ 690.000",
    priceValue: 690_000,
    description: [
      "Flat totalmente mobiliado e decorado, pronto para morar ou alugar. Hotelaria cinco estrelas com serviços de concierge, limpeza e room service.",
      "Unidade no andar alto com vista para o Parque do Povo. Cama king, TV smart, frigobar e cofre. Banheiro com box em vidro temperado.",
      "Localização premium no Itaim Bibi, entre a Faria Lima e o Ibirapuera. Excelente rentabilidade para investidores.",
    ],
    features: [
      { label: "Mobiliado", icon: "gourmet" },
      { label: "Room service", icon: "gourmet" },
      { label: "Concierge", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Piscina", icon: "pool" },
      { label: "Academia", icon: "gym" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "terreno-condominio-tambore",
    title: "Terreno em Condomínio no Tamboré",
    location: "Tamboré, Santana de Parnaíba - SP",
    address: "Alameda Purús, 100 — Tamboré, Santana de Parnaíba - SP",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 0,
    baths: 0,
    parking: 0,
    area: 600,
    price: "R$ 980.000",
    priceValue: 980_000,
    description: [
      "Terreno plano de 600 m² em condomínio de alto padrão no Tamboré, um dos endereços mais valorizados da Grande São Paulo.",
      "Frente para área verde permanente, sem vizinhos nos fundos. Infraestrutura completa com água, esgoto, energia e fibra óptica.",
      "Condomínio com segurança 24h, quadras esportivas, lago e área de lazer. Projeto aprovado para construção de até 350 m².",
    ],
    features: [
      { label: "Área verde", icon: "garden" },
      { label: "Plano", icon: "balcony" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Infraestrutura", icon: "wifi" },
      { label: "Lago", icon: "pool" },
      { label: "Quadras", icon: "gym" },
      { label: "Sem vizinhos", icon: "garden" },
      { label: "Projeto aprovado", icon: "gourmet" },
    ],
  },
  {
    slug: "apartamento-compacto-tatuape",
    title: "Apartamento Compacto no Tatuapé",
    location: "Tatuapé, São Paulo - SP",
    address: "Rua Serra de Bragança, 890 — Tatuapé, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 2,
    baths: 1,
    parking: 1,
    area: 58,
    price: "R$ 450.000",
    priceValue: 450_000,
    description: [
      "Apartamento de dois dormitórios em prédio bem administrado no Tatuapé. Reformado recentemente com piso laminado e pintura nova.",
      "Cozinha com armários planejados, sala integrada e banheiro com box blindex. Prédio com portaria e playground.",
      "A 500 metros do metrô Tatuapé e do Shopping Anália Franco. Ótima relação custo-benefício para primeira moradia.",
    ],
    features: [
      { label: "Reformado", icon: "gourmet" },
      { label: "Playground", icon: "garden" },
      { label: "Portaria", icon: "security" },
      { label: "Piso laminado", icon: "ac" },
      { label: "Metrô próximo", icon: "elevator" },
      { label: "Shopping", icon: "wifi" },
      { label: "Elevador", icon: "elevator" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "casa-geminada-campinas",
    title: "Casa Geminada em Campinas",
    location: "Swiss Park, Campinas - SP",
    address: "Rua José Paulino, 1850 — Swiss Park, Campinas - SP",
    image: "https://images.unsplash.com/photo-1605276374101-de9c4183671c?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1605276374101-de9c4183671c?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 2,
    parking: 2,
    area: 165,
    price: "R$ 720.000",
    priceValue: 720_000,
    description: [
      "Casa geminada em bairro residencial consolidado de Campinas, com quintal nos fundos e garagem coberta para dois carros.",
      "Três dormitórios, sala de estar e jantar, cozinha ampla e área de serviço. Telhado com isolamento térmico instalado.",
      "Swiss Park oferece tranquilidade e proximidade ao centro de Campinas, universidades e hospitais de referência.",
    ],
    features: [
      { label: "Quintal", icon: "garden" },
      { label: "Garagem coberta", icon: "parking" },
      { label: "Muro alto", icon: "security" },
      { label: "Isolamento térmico", icon: "ac" },
      { label: "Churrasqueira", icon: "gourmet" },
      { label: "Área serviço", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "residencial-clube-brooklin",
    title: "Residencial Clube no Brooklin",
    location: "Brooklin, São Paulo - SP",
    address: "Av. Engenheiro Luís Carlos Berrini, 1700 — Brooklin, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 3,
    parking: 2,
    area: 98,
    price: "R$ 1.320.000",
    priceValue: 1_320_000,
    description: [
      "Novo empreendimento no Brooklin Novo com conceito residencial clube. Apartamentos de 98 m² com varanda e vista para o skyline da Berrini.",
      "Infraestrutura completa: piscina adulto e infantil, spa, academia, coworking, pet place e bicicletário. Tomada para carro elétrico na garagem.",
      "Região corporativa com fácil acesso à Marginal Pinheiros, aeroporto de Congonhas e principais empresas multinacionais.",
    ],
    features: [
      { label: "Piscina", icon: "pool" },
      { label: "Spa", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Pet place", icon: "garden" },
      { label: "Coworking", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "penthouse-vista-mar-guaruja",
    title: "Penthouse Vista Mar no Guarujá",
    location: "Enseada, Guarujá - SP",
    address: "Av. Miguel Stéfano, 3500 — Enseada, Guarujá - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 4,
    parking: 3,
    area: 280,
    price: "R$ 3.800.000",
    priceValue: 3_800_000,
    description: [
      "Penthouse de frente para o mar na Enseada do Guarujá, com terraço de 80 m² e piscina privativa. O pôr do sol visto daqui é inesquecível.",
      "Quatro suítes, sala de estar e jantar com cristaleira, cozinha gourmet e lavabo. Elevador privativo com acesso direto ao apartamento.",
      "Condomínio de luxo com praia privativa, marina e restaurante. A 90 minutos de São Paulo pela Rodovia Imigrantes.",
    ],
    features: [
      { label: "Piscina privativa", icon: "pool" },
      { label: "Terraço 80m²", icon: "balcony" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Praia privativa", icon: "garden" },
      { label: "Marina", icon: "gourmet" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "3 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-classico-higienopolis",
    title: "Apartamento Clássico em Higienópolis",
    location: "Higienópolis, São Paulo - SP",
    address: "Rua Maranhão, 320 — Higienópolis, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 2,
    parking: 2,
    area: 140,
    price: "R$ 1.950.000",
    priceValue: 1_950_000,
    description: [
      "Apartamento em edifício histórico de Higienópolis, com pisos originais em taco de madeira e molduras de gesso preservadas. Charme e elegância atemporal.",
      "Três dormitórios amplos, sala com varanda e vista para o Pacaembu, cozinha com copa e dependência de empregada revertida em closet.",
      "Bairro nobre com o Shopping Pátio Higienópolis, teatros, museus e a melhor gastronomia da zona oeste paulistana.",
    ],
    features: [
      { label: "Taco madeira", icon: "gourmet" },
      { label: "Varanda", icon: "balcony" },
      { label: "Portaria", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Vista Pacaembu", icon: "garden" },
      { label: "Closet", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "casa-colonial-campos-do-jordao",
    title: "Casa Colonial em Campos do Jordão",
    location: "Capivari, Campos do Jordão - SP",
    address: "Rua Doutor Adhemar de Barros, 450 — Capivari, Campos do Jordão - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1449844908449-882e69d4d6e0?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1449844908449-882e69d4d6e0?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 3,
    parking: 3,
    area: 310,
    price: "R$ 2.100.000",
    priceValue: 2_100_000,
    description: [
      "Chalé de inspiração europeia no coração do Capivari, a poucos metros da Baden Baden e do teleférico. Lareira a lenha na sala e aquecimento central.",
      "Quatro suítes com closet, sala de jogos, adega subterrânea e deck com ofurô aquecido. Jardim com pinheiros centenários.",
      "Campos do Jordão é o destino de montanha mais procurado do Brasil. Excelente para uso próprio ou locação por temporada.",
    ],
    features: [
      { label: "Lareira", icon: "ac" },
      { label: "Ofurô", icon: "pool" },
      { label: "Aquecimento central", icon: "ac" },
      { label: "Adega", icon: "gourmet" },
      { label: "Jardim", icon: "garden" },
      { label: "Sala de jogos", icon: "gym" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "3 vagas", icon: "parking" },
    ],
  },
  {
    slug: "studio-executivo-faria-lima",
    title: "Studio Executivo na Faria Lima",
    location: "Itaim Bibi, São Paulo - SP",
    address: "Av. Brigadeiro Faria Lima, 3400 — Itaim Bibi, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 1,
    baths: 1,
    parking: 1,
    area: 35,
    price: "R$ 580.000",
    priceValue: 580_000,
    description: [
      "Studio executivo na torre corporativa mais valorizada da Faria Lima. Acabamento premium com piso vinílico, blackout elétrico e ar condicionado central.",
      "Ideal para executivos que trabalham na região. Prédio com academia, piscina no rooftop e restaurante no térreo.",
      "Acesso imediato ao metrô Faria Lima, shoppings JK e Vila Olímpia. Alta valorização e liquidez no mercado.",
    ],
    features: [
      { label: "Rooftop", icon: "balcony" },
      { label: "Restaurante", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar central", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Piscina", icon: "pool" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-vila-olimpia",
    title: "Apartamento na Vila Olímpia",
    location: "Vila Olímpia, São Paulo - SP",
    address: "Rua Funchal, 418 — Vila Olímpia, São Paulo - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 2,
    baths: 2,
    parking: 2,
    area: 85,
    price: "R$ 1.280.000",
    priceValue: 1_280_000,
    description: [
      "Apartamento moderno em torre de alto padrão na Vila Olímpia, com planta bem distribuída e varanda com vista para o skyline corporativo.",
      "Cozinha integrada com bancada em quartzo, suíte com closet e segundo dormitório com armários planejados. Piso porcelanato em todo o imóvel.",
      "Região com excelente infraestrutura gastronômica, shoppings e acesso rápido à Marginal Pinheiros e estação de metrô.",
    ],
    features: [
      { label: "Varanda", icon: "balcony" },
      { label: "Cozinha integrada", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Piscina", icon: "pool" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "casa-unifamiliar-santana-parnaiba",
    title: "Casa Unifamiliar em Santana de Parnaíba",
    location: "Alphaville, Santana de Parnaíba - SP",
    address: "Alameda Grajaú, 310 — Alphaville, Santana de Parnaíba - SP",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 3,
    parking: 3,
    area: 260,
    price: "R$ 1.750.000",
    priceValue: 1_750_000,
    description: [
      "Casa unifamiliar em rua tranquila de Alphaville, com fachada contemporânea e ampla área de convivência integrada à cozinha.",
      "Quatro dormitórios sendo duas suítes, escritório, lavabo e área gourmet coberta com churrasqueira. Quintal com jardim e espaço para piscina.",
      "Próximo a escolas, supermercados e principais vias de acesso à Castello Branco e Rodoanel.",
    ],
    features: [
      { label: "Área gourmet", icon: "gourmet" },
      { label: "Quintal", icon: "garden" },
      { label: "Segurança", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Escritório", icon: "wifi" },
      { label: "Churrasqueira", icon: "gourmet" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "3 vagas", icon: "parking" },
    ],
  },
  {
    slug: "cobertura-perdizes",
    title: "Cobertura em Perdizes",
    location: "Perdizes, São Paulo - SP",
    address: "Rua Cardoso de Almeida, 785 — Perdizes, São Paulo - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 4,
    parking: 3,
    area: 240,
    price: "R$ 3.450.000",
    priceValue: 3_450_000,
    description: [
      "Cobertura linear com terraço de 60 m² e vista aberta para a zona oeste. Ambientes sociais amplos com pé-direito elevado e iluminação natural.",
      "Três suítes, lavabo, cozinha gourmet com ilha e área de serviço completa. Terraço com espaço para jacuzzi e lounge externo.",
      "Perdizes combina vida de bairro com fácil acesso ao Pacaembu, Allianz Parque e principais universidades da região.",
    ],
    features: [
      { label: "Terraço 60m²", icon: "balcony" },
      { label: "Cozinha gourmet", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Jacuzzi", icon: "pool" },
      { label: "Vista livre", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "3 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-aluguel-consolacao",
    title: "Apartamento para Aluguel na Consolação",
    location: "Consolação, São Paulo - SP",
    address: "Rua da Consolação, 2308 — Consolação, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 2,
    baths: 1,
    parking: 1,
    area: 62,
    price: "R$ 4.200",
    priceValue: 4_200,
    description: [
      "Apartamento mobiliado para locação na Consolação, ideal para profissionais que trabalham no centro expandido de São Paulo.",
      "Dois dormitórios com armários, sala integrada à cozinha e banheiro reformado. Prédio com portaria e elevador social.",
      "A poucos minutos do metrô Paulista, Parque Augusta e principais hospitais da região central.",
    ],
    features: [
      { label: "Mobiliado", icon: "gourmet" },
      { label: "Metrô próximo", icon: "elevator" },
      { label: "Portaria", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Elevador", icon: "elevator" },
      { label: "Centro expandido", icon: "wifi" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "galpao-logistico-guarulhos",
    title: "Galpão Logístico em Guarulhos",
    location: "Cumbica, Guarulhos - SP",
    address: "Rod. Presidente Dutra, km 228 — Cumbica, Guarulhos - SP",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 0,
    baths: 2,
    parking: 8,
    area: 1200,
    price: "R$ 4.500.000",
    priceValue: 4_500_000,
    description: [
      "Galpão logístico em condomínio industrial de Guarulhos, com pé-direito de 12 metros e docas para carretas.",
      "Piso industrial reforçado, escritório administrativo climatizado e vestiários. Energia trifásica e sistema de combate a incêndio.",
      "Localização estratégica a 5 km do Aeroporto Internacional de Guarulhos e com acesso direto à Dutra e Rodoanel.",
    ],
    features: [
      { label: "Docas", icon: "parking" },
      { label: "Pé-direito 12m", icon: "balcony" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Escritório", icon: "ac" },
      { label: "Energia trifásica", icon: "wifi" },
      { label: "Acesso Dutra", icon: "elevator" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "8 vagas", icon: "parking" },
    ],
  },
  {
    slug: "chacara-ibiuna",
    title: "Chácara em Ibiúna",
    location: "Ibiúna, São Paulo - SP",
    address: "Estrada Municipal Bairro do Moinho, 45 — Ibiúna - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1449844908449-882e69d4d6e0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 2,
    parking: 6,
    area: 3500,
    price: "R$ 890.000",
    priceValue: 890_000,
    description: [
      "Chácara com 3.500 m² de área total, casa sede de madeira e amplo espaço verde com nascente e pomar.",
      "Três dormitórios, sala com lareira, cozinha rústica e varanda com rede. Quiosque com churrasqueira e fogão a lenha.",
      "Ibiúna oferece clima agradável e tranquilidade a 80 km de São Paulo, ideal para lazer e finais de semana em família.",
    ],
    features: [
      { label: "Nascente", icon: "pool" },
      { label: "Churrasqueira", icon: "gourmet" },
      { label: "Porteira fechada", icon: "security" },
      { label: "Lareira", icon: "ac" },
      { label: "Pomar", icon: "garden" },
      { label: "Quiosque", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "6 vagas", icon: "parking" },
    ],
  },
  {
    slug: "predio-comercial-paulista",
    title: "Prédio Comercial na Paulista",
    location: "Bela Vista, São Paulo - SP",
    address: "Av. Paulista, 1578 — Bela Vista, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 0,
    baths: 4,
    parking: 12,
    area: 850,
    price: "R$ 18.900.000",
    priceValue: 18_900_000,
    description: [
      "Prédio comercial de oito pavimentos na Avenida Paulista, com fachada em vidro e lobby de alto padrão.",
      "Plantas flexíveis para escritórios corporativos, com ar condicionado central, gerador e quatro elevadores sociais.",
      "Endereço corporativo de prestígio com certificação LEED e ocupação consolidada na principal avenida de negócios do país.",
    ],
    features: [
      { label: "Lobby premium", icon: "gourmet" },
      { label: "4 elevadores", icon: "elevator" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Ar central", icon: "ac" },
      { label: "Gerador", icon: "wifi" },
      { label: "Certificação LEED", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "12 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-brooklin-novo",
    title: "Apartamento no Brooklin Novo",
    location: "Brooklin Novo, São Paulo - SP",
    address: "Rua Verbo Divino, 1560 — Brooklin Novo, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 2,
    parking: 2,
    area: 92,
    price: "R$ 1.180.000",
    priceValue: 1_180_000,
    description: [
      "Apartamento em prédio recente no Brooklin Novo, com varanda gourmet e vista para a região da Berrini.",
      "Três dormitórios com suíte, sala em dois ambientes e cozinha americana. Acabamento em porcelanato e esquadrias de alumínio.",
      "Próximo ao Shopping Morumbi, parques e principais escritórios corporativos da zona sul.",
    ],
    features: [
      { label: "Varanda gourmet", icon: "gourmet" },
      { label: "Vista Berrini", icon: "balcony" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Piscina", icon: "pool" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "casa-campo-condominio-jundiai",
    title: "Casa de Campo em Condomínio em Jundiaí",
    location: "Jundiaí, São Paulo - SP",
    address: "Estrada Municipal do Capivari, 890 — Jundiaí - SP",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1449844908449-882e69d4d6e0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 3,
    parking: 4,
    area: 380,
    price: "R$ 1.420.000",
    priceValue: 1_420_000,
    description: [
      "Casa de campo em condomínio fechado em Jundiaí, com terreno de 1.200 m² e vista para área verde preservada.",
      "Quatro suítes, sala com lareira, cozinha ampla e varanda com rede. Piscina aquecida e espaço gourmet integrado.",
      "Condomínio com portaria, lago e trilhas ecológicas. A 60 km de São Paulo pela Anhanguera.",
    ],
    features: [
      { label: "Piscina aquecida", icon: "pool" },
      { label: "Espaço gourmet", icon: "gourmet" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Lareira", icon: "ac" },
      { label: "Vista verde", icon: "garden" },
      { label: "Trilhas", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "4 vagas", icon: "parking" },
    ],
  },
  {
    slug: "studio-aluguel-bela-vista",
    title: "Studio para Aluguel na Bela Vista",
    location: "Bela Vista, São Paulo - SP",
    address: "Rua Peixoto Gomide, 520 — Bela Vista, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 1,
    baths: 1,
    parking: 0,
    area: 32,
    price: "R$ 2.800",
    priceValue: 2_800,
    description: [
      "Studio compacto e funcional na Bela Vista, totalmente mobiliado e pronto para morar.",
      "Ambiente integrado com cama retrátil, cozinha equipada e banheiro com box. Prédio com lavanderia compartilhada.",
      "Região vibrante entre a Paulista e o Jardins, com fácil acesso a metrô, teatros e restaurantes.",
    ],
    features: [
      { label: "Mobiliado", icon: "gourmet" },
      { label: "Cozinha equipada", icon: "gourmet" },
      { label: "Portaria", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Lavanderia", icon: "gym" },
      { label: "Centro cultural", icon: "wifi" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "Sem vaga", icon: "parking" },
    ],
  },
  {
    slug: "terreno-alphaville-eusebio",
    title: "Terreno em Alphaville",
    location: "Alphaville, Barueri - SP",
    address: "Alameda Ébano, 75 — Alphaville, Barueri - SP",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 0,
    baths: 0,
    parking: 0,
    area: 450,
    price: "R$ 1.150.000",
    priceValue: 1_150_000,
    description: [
      "Terreno de 450 m² em condomínio consolidado de Alphaville, com topografia plana e frente para rua arborizada.",
      "Infraestrutura completa de água, esgoto, energia e fibra óptica. Projeto arquitetônico pré-aprovado incluso.",
      "Condomínio com segurança 24h, quadras esportivas e clube. Uma das regiões com maior valorização da Grande São Paulo.",
    ],
    features: [
      { label: "Topografia plana", icon: "balcony" },
      { label: "Projeto incluso", icon: "gourmet" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Infraestrutura", icon: "wifi" },
      { label: "Clube", icon: "pool" },
      { label: "Quadras", icon: "gym" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "Sem vaga", icon: "parking" },
    ],
  },
  {
    slug: "sobrado-osasco-centro",
    title: "Sobrado no Centro de Osasco",
    location: "Centro, Osasco - SP",
    address: "Rua Antonio Agú, 412 — Centro, Osasco - SP",
    image: "https://images.unsplash.com/photo-1605276374101-de9c4183671c?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1605276374101-de9c4183671c?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 2,
    parking: 2,
    area: 140,
    price: "R$ 680.000",
    priceValue: 680_000,
    description: [
      "Sobrado em rua tranquila do centro de Osasco, com sala no piso térreo e dormitórios no andar superior.",
      "Três dormitórios, cozinha ampla, área de serviço e quintal nos fundos com churrasqueira. Garagem coberta para dois carros.",
      "Próximo à estação de trem, comércio local e hospitais. Excelente custo-benefício na região oeste metropolitana.",
    ],
    features: [
      { label: "Quintal", icon: "garden" },
      { label: "Churrasqueira", icon: "gourmet" },
      { label: "Garagem coberta", icon: "parking" },
      { label: "Trem próximo", icon: "elevator" },
      { label: "Área serviço", icon: "garden" },
      { label: "Dois pavimentos", icon: "balcony" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-sacoma",
    title: "Apartamento no Sacomã",
    location: "Sacomã, São Paulo - SP",
    address: "Rua Borges de Figueiredo, 1120 — Sacomã, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 2,
    baths: 1,
    parking: 1,
    area: 55,
    price: "R$ 395.000",
    priceValue: 395_000,
    description: [
      "Apartamento de dois dormitórios no Sacomã, em prédio com portaria e área de lazer completa.",
      "Sala e cozinha integradas, banheiro com box e dormitórios com armários embutidos. Reformado em 2024.",
      "A 800 metros do metrô Sacomã e próximo ao Shopping Plaza Sul. Ótima opção para primeira moradia.",
    ],
    features: [
      { label: "Reformado", icon: "gourmet" },
      { label: "Área de lazer", icon: "pool" },
      { label: "Portaria", icon: "security" },
      { label: "Metrô próximo", icon: "elevator" },
      { label: "Playground", icon: "garden" },
      { label: "Shopping", icon: "wifi" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "flat-aluguel-jardins",
    title: "Flat para Aluguel nos Jardins",
    location: "Jardins, São Paulo - SP",
    address: "Alameda Campinas, 890 — Jardins, São Paulo - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 1,
    baths: 1,
    parking: 1,
    area: 45,
    price: "R$ 6.500",
    priceValue: 6_500,
    description: [
      "Flat de alto padrão nos Jardins com serviços de hotelaria, ideal para executivos em trânsito ou locação de curto prazo.",
      "Suíte mobiliada com cama king, TV smart e banheiro com amenities premium. Vista para a Alameda Campinas.",
      "Hotel com restaurante, spa, academia e concierge. A poucos passos das melores boutiques e restaurantes da cidade.",
    ],
    features: [
      { label: "Serviço hotel", icon: "gourmet" },
      { label: "Spa", icon: "pool" },
      { label: "Concierge", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Restaurante", icon: "gourmet" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "espaco-comercial-vila-leopoldina",
    title: "Espaço Comercial na Vila Leopoldina",
    location: "Vila Leopoldina, São Paulo - SP",
    address: "Av. Queiroz Filho, 1560 — Vila Leopoldina, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 0,
    baths: 2,
    parking: 4,
    area: 180,
    price: "R$ 12.000",
    priceValue: 12_000,
    description: [
      "Sala comercial em edifício corporativo na Vila Leopoldina, com recepção privativa e layout aberto.",
      "Pé-direito de 3,5 metros, piso elevado para cabeamento e duas vagas de garagem cobertas. Ar condicionado central.",
      "Região em plena expansão com acesso à Marginal Pinheiros, estação Villa-Lobos e polo gastronômico da Leopoldina.",
    ],
    features: [
      { label: "Layout aberto", icon: "balcony" },
      { label: "Recepção", icon: "gourmet" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Ar central", icon: "ac" },
      { label: "Elevador", icon: "elevator" },
      { label: "Marginal próxima", icon: "wifi" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "4 vagas", icon: "parking" },
    ],
  },
  {
    slug: "cobertura-aluguel-santos",
    title: "Cobertura para Aluguel em Santos",
    location: "Boqueirão, Santos - SP",
    address: "Av. Conselheiro Nébias, 450 — Boqueirão, Santos - SP",
    badge: "DESTAQUE",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 3,
    parking: 2,
    area: 200,
    price: "R$ 15.000",
    priceValue: 15_000,
    description: [
      "Cobertura mobiliada para locação no Boqueirão, a duas quadras da praia, com terraço e churrasqueira.",
      "Três suítes, sala ampla com vista parcial para o mar e cozinha gourmet equipada. Mobiliário de designer incluso.",
      "Santos oferece qualidade de vida litorânea com infraestrutura completa e fácil acesso à capital paulista.",
    ],
    features: [
      { label: "Terraço", icon: "balcony" },
      { label: "Churrasqueira", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Vista mar", icon: "garden" },
      { label: "Mobiliado", icon: "gourmet" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "casa-condominio-nova-campinas",
    title: "Casa em Condomínio em Nova Campinas",
    location: "Nova Campinas, Campinas - SP",
    address: "Rua José Paulino, 2200 — Nova Campinas, Campinas - SP",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 4,
    baths: 4,
    parking: 4,
    area: 300,
    price: "R$ 2.280.000",
    priceValue: 2_280_000,
    description: [
      "Casa em condomínio fechado em Nova Campinas, com projeto moderno e acabamento de alto padrão.",
      "Quatro suítes, sala com pé-direito duplo, cozinha gourmet e área de lazer com piscina e spa.",
      "Condomínio com segurança reforçada, quadras e área verde. Próximo ao Shopping Iguatemi Campinas.",
    ],
    features: [
      { label: "Piscina", icon: "pool" },
      { label: "Spa", icon: "gourmet" },
      { label: "Segurança 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Pé-direito duplo", icon: "balcony" },
      { label: "Quadras", icon: "gym" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "4 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-lancamento-mooca",
    title: "Apartamento Lançamento na Mooca",
    location: "Mooca, São Paulo - SP",
    address: "Rua Bresser, 1850 — Mooca, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 2,
    baths: 2,
    parking: 1,
    area: 68,
    price: "R$ 620.000",
    priceValue: 620_000,
    description: [
      "Lançamento na Mooca com plantas de 68 m², varanda integrada e acabamento entregue pela construtora.",
      "Dois dormitórios com suíte, cozinha americana e lavabo. Infraestrutura de lazer com piscina, academia e salão de festas.",
      "Bairro tradicional com forte valorização, metrô próximo e comércio consolidado ao redor.",
    ],
    features: [
      { label: "Lançamento", icon: "balcony" },
      { label: "Varanda", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Piscina", icon: "pool" },
      { label: "Academia", icon: "gym" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "1 vaga", icon: "parking" },
    ],
  },
  {
    slug: "edificio-residencial-perdizes",
    title: "Edifício Residencial em Perdizes",
    location: "Perdizes, São Paulo - SP",
    address: "Rua Turiassu, 650 — Perdizes, São Paulo - SP",
    badge: "LANÇAMENTO",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 3,
    parking: 2,
    area: 105,
    price: "R$ 1.480.000",
    priceValue: 1_480_000,
    description: [
      "Unidade em edifício residencial de alto padrão em Perdizes, com fachada assinada e áreas comuns completas.",
      "Três dormitórios sendo uma suíte master, varanda gourmet e cozinha integrada. Tomada para carro elétrico na garagem.",
      "Perdizes é um dos bairros mais desejados da zona oeste, com parques, universidades e gastronomia de referência.",
    ],
    features: [
      { label: "Rooftop", icon: "balcony" },
      { label: "Varanda gourmet", icon: "gourmet" },
      { label: "Portaria 24h", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Academia", icon: "gym" },
      { label: "Piscina", icon: "pool" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
  {
    slug: "apartamento-alto-da-lapa",
    title: "Apartamento no Alto da Lapa",
    location: "Alto da Lapa, São Paulo - SP",
    address: "Rua Coriolano, 1850 — Alto da Lapa, São Paulo - SP",
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=900&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f64d4cd21?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=400&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&q=80&auto=format&fit=crop",
    ],
    beds: 3,
    baths: 2,
    parking: 2,
    area: 115,
    price: "R$ 980.000",
    priceValue: 980_000,
    description: [
      "Apartamento amplo no Alto da Lapa, em prédio arborizado com vista para a Serra da Cantareira.",
      "Três dormitórios, sala em dois ambientes com varanda, cozinha com despensa e dependência revertida em home office.",
      "Bairro residencial tranquilo com fácil acesso à Lapa, Pompéia e Marginal Tietê. Excelente qualidade de vida.",
    ],
    features: [
      { label: "Vista serra", icon: "balcony" },
      { label: "Varanda", icon: "gourmet" },
      { label: "Portaria", icon: "security" },
      { label: "Ar condicionado", icon: "ac" },
      { label: "Home office", icon: "wifi" },
      { label: "Área verde", icon: "garden" },
      { label: "Wi-Fi", icon: "wifi" },
      { label: "2 vagas", icon: "parking" },
    ],
  },
];

type PropertyMeta = {
  purpose: PropertyPurpose;
  propertyType: PropertyType;
  condominium?: string;
  code: string;
};

const PROPERTY_META: Record<string, PropertyMeta> = {
  "casa-em-condominio": {
    purpose: "comprar",
    propertyType: "Casa em Condomínio",
    condominium: "Alphaville Residencial One",
    code: "LOT-001",
  },
  "edificio-lotus-residence": {
    purpose: "comprar",
    propertyType: "Edifício",
    condominium: "Lótus Residence",
    code: "LOT-002",
  },
  "apartamento-premium": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-003",
  },
  "cobertura-duplex-jardins": {
    purpose: "comprar",
    propertyType: "Cobertura",
    code: "LOT-004",
  },
  "studio-moderno-pinheiros": {
    purpose: "alugar",
    propertyType: "Apartamento",
    code: "LOT-005",
  },
  "casa-de-campo-atibaia": {
    purpose: "comprar",
    propertyType: "Casa de campo",
    code: "LOT-006",
  },
  "apartamento-frente-mar-santos": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-007",
  },
  "loft-industrial-vila-madalena": {
    purpose: "alugar",
    propertyType: "Espaço comercial",
    code: "LOT-008",
  },
  "mansao-alto-padrao-morumbi": {
    purpose: "comprar",
    propertyType: "Casa",
    code: "LOT-009",
  },
  "apartamento-garden-moema": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-010",
  },
  "casa-terrea-granja-viana": {
    purpose: "comprar",
    propertyType: "Casa em Condomínio",
    condominium: "Granja Viana Clube",
    code: "LOT-011",
  },
  "flat-mobiliado-itaim-bibi": {
    purpose: "alugar",
    propertyType: "Apartamento",
    code: "LOT-012",
  },
  "terreno-condominio-tambore": {
    purpose: "comprar",
    propertyType: "Terreno em Condomínio",
    condominium: "Condomínio Tamboré",
    code: "LOT-013",
  },
  "apartamento-compacto-tatuape": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-014",
  },
  "casa-geminada-campinas": {
    purpose: "comprar",
    propertyType: "Sobrado",
    code: "LOT-015",
  },
  "residencial-clube-brooklin": {
    purpose: "comprar",
    propertyType: "Condomínio",
    condominium: "Residencial Clube Brooklin",
    code: "LOT-016",
  },
  "penthouse-vista-mar-guaruja": {
    purpose: "comprar",
    propertyType: "Cobertura",
    code: "LOT-017",
  },
  "apartamento-classico-higienopolis": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-018",
  },
  "casa-colonial-campos-do-jordao": {
    purpose: "comprar",
    propertyType: "Casa de campo",
    code: "LOT-019",
  },
  "studio-executivo-faria-lima": {
    purpose: "alugar",
    propertyType: "Apartamento",
    code: "LOT-020",
  },
  "apartamento-vila-olimpia": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-021",
  },
  "casa-unifamiliar-santana-parnaiba": {
    purpose: "comprar",
    propertyType: "Casa unifamiliar",
    code: "LOT-022",
  },
  "cobertura-perdizes": {
    purpose: "comprar",
    propertyType: "Cobertura",
    code: "LOT-023",
  },
  "apartamento-aluguel-consolacao": {
    purpose: "alugar",
    propertyType: "Apartamento",
    code: "LOT-024",
  },
  "galpao-logistico-guarulhos": {
    purpose: "comprar",
    propertyType: "Galpão",
    code: "LOT-025",
  },
  "chacara-ibiuna": {
    purpose: "comprar",
    propertyType: "Chácara",
    code: "LOT-026",
  },
  "predio-comercial-paulista": {
    purpose: "comprar",
    propertyType: "Prédio comercial",
    code: "LOT-027",
  },
  "apartamento-brooklin-novo": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-028",
  },
  "casa-campo-condominio-jundiai": {
    purpose: "comprar",
    propertyType: "Casa de campo em condomínio",
    condominium: "Residencial Capivari",
    code: "LOT-029",
  },
  "studio-aluguel-bela-vista": {
    purpose: "alugar",
    propertyType: "Apartamento",
    code: "LOT-030",
  },
  "terreno-alphaville-eusebio": {
    purpose: "comprar",
    propertyType: "Terreno em Condomínio",
    condominium: "Alphaville Residencial 10",
    code: "LOT-031",
  },
  "sobrado-osasco-centro": {
    purpose: "comprar",
    propertyType: "Sobrado",
    code: "LOT-032",
  },
  "apartamento-sacoma": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-033",
  },
  "flat-aluguel-jardins": {
    purpose: "alugar",
    propertyType: "Apartamento",
    code: "LOT-034",
  },
  "espaco-comercial-vila-leopoldina": {
    purpose: "alugar",
    propertyType: "Espaço comercial",
    code: "LOT-035",
  },
  "cobertura-aluguel-santos": {
    purpose: "alugar",
    propertyType: "Cobertura",
    code: "LOT-036",
  },
  "casa-condominio-nova-campinas": {
    purpose: "comprar",
    propertyType: "Casa em Condomínio",
    condominium: "Condomínio Nova Campinas",
    code: "LOT-037",
  },
  "apartamento-lancamento-mooca": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-038",
  },
  "edificio-residencial-perdizes": {
    purpose: "comprar",
    propertyType: "Edifício",
    condominium: "Residencial Turiassu",
    code: "LOT-039",
  },
  "apartamento-alto-da-lapa": {
    purpose: "comprar",
    propertyType: "Apartamento",
    code: "LOT-040",
  },
};

const upsert = db.prepare(`
  INSERT INTO properties (
    slug, title, location, address, badge, purpose, property_type, condominium, code,
    image, gallery, beds, baths, parking, area, price, price_value, description, features, created_at
  ) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
  )
  ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    location = excluded.location,
    address = excluded.address,
    badge = excluded.badge,
    purpose = excluded.purpose,
    property_type = excluded.property_type,
    condominium = excluded.condominium,
    code = excluded.code,
    image = excluded.image,
    gallery = excluded.gallery,
    beds = excluded.beds,
    baths = excluded.baths,
    parking = excluded.parking,
    area = excluded.area,
    price = excluded.price,
    price_value = excluded.price_value,
    description = excluded.description,
    features = excluded.features
`);

export function syncPropertySearchMetadata() {
  const sync = db.prepare(`
    UPDATE properties SET
      purpose = ?,
      property_type = ?,
      condominium = ?,
      code = ?
    WHERE slug = ?
  `);

  let updated = 0;
  for (const [slug, meta] of Object.entries(PROPERTY_META)) {
    const result = sync.run(
      meta.purpose,
      meta.propertyType,
      meta.condominium ?? null,
      meta.code,
      slug,
    );
    updated += Number(result.changes);
  }

  if (updated > 0) {
    console.log(`Synced search metadata for ${updated} properties.`);
  }
}

export function seedDatabase() {
  for (const p of SEED_PROPERTIES) {
    const meta = PROPERTY_META[p.slug] ?? {
      purpose: "comprar" as const,
      propertyType: "Apartamento" as const,
      code: p.slug.toUpperCase().replace(/-/g, "_"),
    };

    upsert.run(
      p.slug,
      p.title,
      p.location,
      p.address,
      p.badge ?? null,
      meta.purpose,
      meta.propertyType,
      meta.condominium ?? null,
      meta.code,
      p.image,
      JSON.stringify(p.gallery),
      p.beds,
      p.baths,
      p.parking,
      p.area,
      p.price,
      p.priceValue,
      JSON.stringify(p.description),
      JSON.stringify(p.features),
      currentTimestampIso(),
    );
  }
  console.log(`Seeded ${SEED_PROPERTIES.length} properties (${propertyCount()} total in database).`);
}

const isDirectRun = process.argv[1]?.replace(/\\/g, "/").endsWith("/db/seed.ts");
if (isDirectRun) {
  seedDatabase();
}
